# 첫 번째 스테이지: React 애플리케이션 빌드
FROM node:18.17.1-slim as builder

# 작업 폴더를 만들고 npm 설치
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY ./frontend/package* /usr/src/app/

# 버전 18에 맞게 설치 
RUN npm install -g npm@10.0.0
RUN npm install react react-dom
RUN npm install --save 
RUN npm install --save --save-exact react-scripts@5.0.1 --silent

# 소스를 작업폴더로 복사하고 빌드
COPY ./frontend /usr/src/app
RUN npm run build

# 두 번째 스테이지: Nginx 서버 설정 및 빌드한 애플리케이션 배포
FROM nginx:latest 

# 로그 디렉토리 생성
RUN mkdir -p /var/log/nginx/log

# Nginx 설정
RUN rm -rf /etc/nginx/conf.d
COPY ./Nginx/conf /etc/nginx

# 첫 번째 스테이지에서 빌드한 결과물을 Nginx로 복사
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# 80포트 오픈하고 nginx 실행
EXPOSE 80